// <auto-generated />
using System;
using GrpcServer.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrpcServer.Migrations
{
    [DbContext(typeof(TalkzContext))]
    [Migration("20230418152700_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GrpcServer.Entities.Chat", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("userId");

                    b.Property<int>("ChatId")
                        .HasColumnType("int(11)")
                        .HasColumnName("chatId");

                    b.Property<sbyte>("IsListed")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("isListed");

                    b.HasKey("UserId", "ChatId")
                        .HasName("PRIMARY");

                    b.ToTable("chats", (string)null);
                });

            modelBuilder.Entity("GrpcServer.Entities.Friendlist", b =>
                {
                    b.Property<int>("UserId1")
                        .HasColumnType("int(11)")
                        .HasColumnName("userId1");

                    b.Property<int>("UserId2")
                        .HasColumnType("int(11)")
                        .HasColumnName("userId2");

                    b.Property<bool?>("IsFriend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isFriend")
                        .HasDefaultValueSql("false");

                    b.HasKey("UserId1", "UserId2")
                        .HasName("PRIMARY");

                    b.ToTable("friendlist", (string)null);
                });

            modelBuilder.Entity("GrpcServer.Entities.Message", b =>
                {
                    b.Property<int>("FromId")
                        .HasColumnType("int(11)")
                        .HasColumnName("fromId");

                    b.Property<long>("MessageTimestamp")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("messageTimestamp");

                    b.Property<int>("ChatId")
                        .HasColumnType("int(11)")
                        .HasColumnName("chatId");

                    b.Property<bool?>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isEdited")
                        .HasDefaultValueSql("0");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isRead")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Message1")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.HasKey("FromId", "MessageTimestamp")
                        .HasName("PRIMARY");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("GrpcServer.Entities.Usercredential", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("userId");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("ProfileImgB64")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasColumnName("profileImgB64")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("username");

                    b.Property<int>("UsernameId")
                        .HasColumnType("int(11)")
                        .HasColumnName("usernameId");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.ToTable("usercredentials", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
